parameters:
  #...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  App\:
    resource: '../src/*'
    exclude: '../src/{Manager,Controller,Config,Auth,Middleware,Factory,Kernel.php}'
