parameters:
  #...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  PSVneo\:
    resource: '../src/*'
    exclude: '../src/{Request,App.php}'

  PSVneo\Service\ConfigurationFileService:
    public: true