parameters:
  privateKey: '%env(default:privateKeyPath:string:PRIVATE_KEY)%'
  privateKeyPath: '%env(default:empty:string:PRIVATE_KEY_PATH)%'
  publicKey: '%env(default:publicKeyPath:string:PUBLIC_KEY)%'
  publicKeyPath: '%env(default:empty:string:PUBLIC_KEY_PATH)%'
  empty: ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  OmegaCode\JwtSecuredApiCore\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Composer,Error,Configuration,Factory,Extension,Event,Collection,Route,Kernel.php,Constants.php,ConfigurationDirectoryProvider.php}'

  OmegaCode\JwtSecuredApiCore\Auth\JsonWebTokenAuth:
    arguments:
      $issuer: '%env(string:JWT_ISSUER)%'
      $lifetime: '%env(int:JWT_LIFETIME)%'
      $privateKey: '%privateKey%'
      $publicKey: '%publicKey%'

  Symfony\Component\EventDispatcher\EventDispatcher:
    public: true

  Slim\App:
    synthetic: true

  Monolog\Logger:
    synthetic: true

  OmegaCode\JwtSecuredApiCore\Command\ClearCacheCommand:
    tags:
      - { name: 'console.command', command: 'cache:clear' }

  OmegaCode\JwtSecuredApiCore\Command\GenerateKeysCommand:
    tags:
      - { name: 'console.command', command: 'api:keys:generate' }

  OmegaCode\JwtSecuredApiCore\Command\Client\AddClientCommand:
    tags:
      - { name: 'console.command', command: 'api:client:add' }

  OmegaCode\JwtSecuredApiCore\Command\Client\ListClientCommand:
    tags:
      - { name: 'console.command', command: 'api:client:list' }
