services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  OmegaCode\JwtSecuredApiCore\:
    resource: '../src/*'
    exclude: '../src/{Auth,DependencyInjection,Composer,Error,Configuration,Factory,Extension,Event,Collection,Route,Kernel.php,Constants.php,ConfigurationDirectoryProvider.php}'

  Symfony\Component\EventDispatcher\EventDispatcher:
    public: true

  OmegaCode\JwtSecuredApiCore\Auth\JWT\JWTAuthInterface:
    synthetic: true

  Slim\App:
    synthetic: true

  Monolog\Logger:
    synthetic: true

  OmegaCode\JwtSecuredApiCore\Core\Api:
    class: OmegaCode\JwtSecuredApiCore\Core\Api
    arguments:
      - '@Slim\App'
      - '@Symfony\Component\EventDispatcher\EventDispatcher'
      - '@service_container'

  OmegaCode\JwtSecuredApiCore\Command\ClearCacheCommand:
    tags:
      - { name: 'console.command', command: 'cache:clear' }

  OmegaCode\JwtSecuredApiCore\Command\GenerateKeysCommand:
    tags:
      - { name: 'console.command', command: 'api:keys:generate' }

  OmegaCode\JwtSecuredApiCore\Command\Client\AddClientCommand:
    tags:
      - { name: 'console.command', command: 'api:client:add' }

  OmegaCode\JwtSecuredApiCore\Command\Client\ListClientCommand:
    tags:
      - { name: 'console.command', command: 'api:client:list' }
