services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  OmegaCode\JwtSecuredApiCore\:
    resource: '../src/*'
    exclude: '../src/{Config,Middleware,Factory,Kernel.php,Router.php,Constants.php}'

  OmegaCode\JwtSecuredApiCore\Auth\JsonWebTokenAuth:
    arguments:
      $issuer: '%env(string:JWT_ISSUER)%'
      $lifetime: '%env(int:JWT_LIFETIME)%'
      $privateKeyPath: '%env(string:PRIVATE_KEY_PATH)%'
      $publicKeyPath: '%env(string:PUBLIC_KEY_PATH)%'
