routes:
  -
    name: auth.login
    route: /auth
    methods: [post,options]
    action: OmegaCode\JwtSecuredApiCore\Action\Auth\LoginAction
  -
    name: auth.verify
    route: /auth/verify
    methods: [post,options]
    action: OmegaCode\JwtSecuredApiCore\Action\Auth\VerifyAction
